version: '3'
services:
  client-crud:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
      - "4300:4300"
    networks:
      - networkName

networks:
  networkName:
    driver: bridge