name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - run: "npm install"
      - run: "npx nx run-many --parallel --target=serve --projects=client-crud"
